application: goregex
version: 1
runtime: go
api_version: go1

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /css
  static_dir: gore/css

- url: /js
  static_dir: gore/js

- url: /
  static_files: gore/index.html
  upload: gore/index.html

- url: /.*
  script: _go_app
